### ISSUE TITLE
Trigger on multiple branches/tags

### ISSUE THREAD

**Issue by CAFxX** [concourse/git-resource#112]
On docker hub it is very convenient to be able to trigger automated builds using regular expressions for branch or tag names. 

On concourse right now this is not possible and we're forced to workaround this by writing long bash scripts :( Would it be possible to extend the git resource to trigger when one of multiple branches/tags is modified?

**Comment by chendrix** [comment]
Hi there!

First the bad news, and then the good. We are unlikely to add support for triggering on multiple branches/tags to this git-resource, because it's *meant* to track the the git history of a single branch. The version history is a history of the commits of a git repo branch.

The good news, however, is twofold. 
* One: I'd be interested in better understanding your use case. What are you trying to solve for, what are you trying to get accomplished? If we better understand your use case, maybe we can find an area that Concourse could support in the future.
* Two: You may be able to leverage some existing resources such as the [git-branch-heads-resource](https://github.com/vito/git-branch-heads-resource)

**Comment by CAFxX** [comment]
> One: I'd be interested in better understanding your use case. What are you trying to solve for, what are you trying to get accomplished?

Primary use case would be run unit (+integration?) tests every time a branch (exluding master) is pushed/updated (this normally happens either immediately before a PR is opened or when it's updated, so having the test results for that branch in the PR will speed up reviews)

**Comment by chendrix** [comment]
@CAFxX have you looked at integrating the [pullrequest-resource](https://github.com/jtarchie/pullrequest-resource)? Does that satisfy your needs?

**Comment by patmaddox** [comment]
@chendrix You asked about use cases for this. The basic case is that we want to run tests on branches before merging them into main.

`pullrequest-resource` is insufficient because GitHub isn't the only place to use git :) Also, PRs aren't the only workflow - our team for example works in branches, and merges directly to master when the work is done, no PRs involved.

So what concourse currently has is (if I'm understanding correctly):

- `git-resource`: tracks a single branch
- `github-pr`: provider and workflow-specific multiple branches

There's a whole world of usages between those two. Multiple branches on a private git repo is just one example.
