### ISSUE TITLE
Pipeline is failing to clone repository: "Please make sure you have the correct access rights and the repository exists."

### ISSUE THREAD

**Issue by aashah** [concourse/git-resource#117]
The CAPI CloudFoundry team been seeing the following error appear intermittently for several github git-resources in our [pipeline](https://http://capi.ci.cf-app.com/):

```
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/build/get'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Initially, the recommendation was to use our private key to do the clone (not https, and by adding a `private_key` to our resource config) as there was a possibility of github rate limiting us. We made this change, and have not seen the error go away.

We do not think this is a network flake, as we have not seen other network flakes in other jobs. Re-running the jobs when this happens usually fixes them.

We are running Concourse v2.6.0.

Let me know if there is any other information I can provide.

**Comment by aashah** [comment]
During a conversation in Slack, we were asked to see if there was a specific worker that this failure appeared on. This is because at random points in the week, several resources/jobs would go orange with this failure at the same time...usually resolves itself after 10 minutes.

There was no specific worker that the containers were failing on, we saw containers on 3 different workers fail for this reason at the same time.

**Comment by joshzarrabi** [comment]
It seems like the problem here was that the NAT box did not allow ICMP messages. Our theory (thanks @vito) is that some routers on the way to github.com would not split packets that exceeded their MTU, but rather would just drop them and then send ICMP messages back to the sender saying "please send smaller packets". Because ICMP was turned off, however, the concourse instance in question would just send packets and get no response on some of them, explaining the weird hanging behavior. The intermittency can be explained because only some routers have this behavior, and if you were lucky enough not to hit those everything would go smoothly. 

See here for a long explanation: https://www.cisco.com/c/en/us/support/docs/ip/generic-routing-encapsulation-gre/25885-pmtud-ipfrag.html

Closing this for now unless it comes up again.

**Comment by joshzarrabi** [comment]
Nevermind lol

**Comment by jtarchie** [comment]
This is currently inactionable because this is a very generic git message. Possible issues:

* the repo doesn't exist
* the private key is invalid
* the key does not have permissions
* the remote server is having issues

If this occurs again, please try to validate these are not your culprits.
