### ISSUE TITLE
File containing sha of HEAD

### ISSUE THREAD

**Issue by oppegard** [concourse/git-resource#13]
It'd be handy if there was a file containing the sha of the git repo checked out. Currently, the way to get this is via `git rev-parse HEAD`.

**Comment by jchesterpivotal** [comment]
I feel like this and #9 are related to a common need -- capturing git information in a structured way.

For inspiration, the [git-commit](https://github.com/ktoso/maven-git-commit-id-plugin/) plugin for Maven generates a `git.properties` file with All The Things™ in it, which Spring Boot is able to [recognise and expose](https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html#production-ready-git-commit-information) through an optional management endpoint.

**Comment by xoebus** [comment]
#9 is just about visual metadata and less about having additional information in the repository.

Unfortunately, I'm probably going to close this as a WONTFIX. I'd rather that people kept their scripts decoupled from Concourse which means avoiding things like this as they increase the surface area of the product significantly for limited benefit. The `git rev-parse HEAD` solution is nice because it will work forever and is CI system agnostic.
