### ISSUE TITLE
Check failing with exit status 137

### ISSUE THREAD

**Issue by Shugyousha** [concourse/git-resource#133]
I am using Concourse v3.3.2. Since I started to use Vault for credential management two of my resources get stuck in the checking phase with the following error:

```
resource script '/opt/resource/check []' failed: exit status 137

stderr:
Cloning into '/tmp/git-resource-repo-cache'...
```

For both git repos I use 'username' and 'password' source parameters with bracketed parameters, like (( user )), used through Vault.

I suspect that the error may have something to do with repo size. I use about 5 other git repo resources using the same credentials and they seem to work just fine. Both failing repos are fairly large however. One of them is 353MB and the other one 508MB so it could be that they time out? I have gotten them to work (check and clone) successfully before but at the moment they haven't succeeded for a few hours.

Please let me know if I can help you debug this issue by giving you more details.

***edit***:

It looks like it could be a result of docker killing the container:

https://github.com/moby/moby/issues/21083

If that indeed is the case, it would be good to have a timeout/resource limit option for resources as well.

I found one workaround that makes the check work at least occasionally. You can run

```
fly -t yourserver check-resource -r pipeline/problematic-gitrepo
fly -t yourserver intercept --check pipeline/problematic-gitrepo
```

When doing this, since we are logged into the container doing the checking, it won't be killed. What sometimes happens in our case is the following error.

```
pq: insert or update on table "resource_config_check_sessions" violates foreign key constraint "resource_config_check_sessions_resource_config_id_fkey"
```

In other cases the checking actually works (for us). Of course this is just a last resort-workaround and we should figure out why this happens in the first case.

**Comment by barutm** [comment]
I have the exact same issue, and it started to occur as soon as I integrated Concourse with Vault.

**Comment by bitprophet** [comment]
I'm having similar symptoms, with the following differences / additions:

- I jumped from Concourse 3.2.x straight to 3.3.4 in order to test Vault integration. Was not having this issue on 3.2.x.
  - FTR, I am using the standalone binaries on Ubuntu 16.04 EC2 systems.
- Using a (now Vault-derived) SSH key instead of password authentication, for the git repository resource (it's GitHub, FWIW)
- The stderr from the resource check output does _not_ contain the `Cloning into ...` output from git, as in the OP; mine stops right after what I assume is ssh-agent output, stating `Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)`
- It is intermittent, happening maybe a half-dozen times a minute if I run `fly check-resource` in a shell loop. Most of the time, the check is succeeding just fine.
  - Note: I am only doing it in the shell as a means of trying to detect correlated log messages; it occurs via naturally-scheduled checks as well, and the stderr display shows up in the web app, same as from `fly`. (As one would expect since this is all API driven.)
- Both successful and failed resource checks take about 1 second to execute either way. (The repo in question is only about 17 MB so it's unlikely to be the sort of time/size related constraint the OP may be experiencing.)
- The following (scrubbed) log line examples are clearly correlated to the failures (I confirmed the timestamps and so forth):
  - On each failure (so, a few times a minute):
    ```
    {
      "source": "atc",
      "message": "atc.check-resource.check-failed",
      "log_level": 1,
      "data": {"exit-status": 137, "session": "2715"}
    }
    ```
  - Every ~3-5 minutes, one of these also pops up (suspect this might be the "real" scheduled check as opposed to my manual ones?):
    ```
    {
      "source": "atc",
      "message": "atc.syncer.lab:radar.scan-resource.interval-runner.tick.check-failed",
      "log_level": 1,
      "data": {"exit-status": 137, "pipeline-scoped-name": "<pipeline-name>:resource:<resource-name>"}
    }
    ```
- Conversely, I _am not_ seeing any _other_ (ATC) log messages correlate strongly with these incidents. Not the messages about renewing the Vault token (though a race condition there would presumably be a terminal issue so it can't be that); no messages from the container system; etc.
- Writing the previous bullet point prompted me to remember I hadn't checked the _worker_ log yet (system consists of one ATC and one worker cohabiting)...
- Checked the worker's logs in tandem, and there are no obvious errors to report there, though I am seeing what _might_ be a race?
  - execution of the check (`garden.api.garden-server.run.spawned`) at, say, ts `...660.987`
  - container (volume?) destruction (`guardian.destroy.destroy.started`) at ts `...662.198`
    - followed by a few more `delete`/`destroy` messages in the same vein, all within the same second
  - receipt of check result (???) (`guardian.api.garden-server.run.exited`) at `...662.446`
  - then finally the ATC-level complaint with the 137 exit code, at `...662.450`
  - I can't prove that the destroy messages are actually related, but this is a non-busy server (it's a test system that I am the only user of, and there aren't many build triggers in place)
  - But I can say that all successful checks have effectively adjacent `run.spawned` and `run.exited` lines (with either no, or only heartbeat, messages between) and that similarly, all errors I can see in my logs exhibit the abovementioned ordering (with destroy in-between the subprocess spawn/exit).

Going to do a bit more digging to see if I can pin down the proximate cause. E.g., does this happen _without_ vault integration active (indicating that it may be due to an unrelated new change in 3.3.x)?

Also of note, I'm also seeing folks talk about this in Slack, such as `@sgoller` and `@jtarchie` back in mid-July. I've also found what smell like a bunch of related issues on the main tracker:

- https://github.com/concourse/concourse/issues/1366 - not a perfect match but seems similar
- https://github.com/concourse/concourse/issues/1392 - comments here strongly imply that Vault use is a/the trigger
- https://github.com/concourse/concourse/issues/1413 - again not an exact match but might explain the issue?
- https://github.com/concourse/concourse/issues/1424
- https://github.com/concourse/concourse/issues/1297 - presumably out in 3.4.0 any day now, _may_ help (though in my case, only if it incidentally fixes what seems like an over-aggressive gc; my problem is almost certainly not due to snowballing volumes!)

**Comment by bitprophet** [comment]
In trying to quantify my symptoms before some quick "does restarting the worker help?" "does reverting Vault usage help?" tests, I find that when the issue happens, it seems to be very strongly 30s-periodic (with nearly all intervals between the issue being 30, 60 or 120s) - again implicating either the resource cache cleanup, or gc, interval, as both default to 30s.

**Comment by bitprophet** [comment]
Quick update, it's definitely only when vault integration is in use:

- No vault args given to `concourse web`, period, and secrets manually injected to `set-pipeline`: no problems after 5+ minutes
- Vault args given to `concourse-web`, but pipeline configs unchanged (thus, no need to talk to vault): ditto, 5+ minutes, no errors
- Back to previous state of pipeline configs having unresolved `((params))`, prompting vault connectivity: same as before, errors every 30/60/90/120/etc seconds.

I haven't looked at how exactly integration works, but if it's causing additional containers to spin up (i.e. if it uses a container-borne process to talk to Vault? similar to how resource checks work?) maybe that's the proximate cause. Not sure. Hoping 3.4.0 will incidentally fix the issue.

**Comment by topherbullock** [comment]
The Concourse team have observed this on our own cluster. 

Nice to have some other reproduction cases confirm that the Vault integration is the issue; this is a weird one with a lot of various symptoms, and multiple potential causes. 

It seems like the resource configurations are invalidated as soon as a container is created for them, and if GC is about to run, those containers are immediately reaped from the database. Interestingly enough, it seems to always be the exact same resources which fail consistently in this way, even between ATC and Worker restarts.

concourse/concourse#1413 is the aggregate issue, which captures some of the errors related to this.

**Comment by vito** [comment]
Rolling this in to https://github.com/concourse/concourse/issues/1413 (see https://github.com/concourse/concourse/issues/1413#issuecomment-322549088)
