### ISSUE TITLE
The common script should remove the prefix https://github.com

### ISSUE THREAD

**Issue by vinhtran2905** [concourse/git-resource#279]
From git resource log shows the URL incorrectly so that user can not click the git commit log 
 /https://github.abc.com/xxxxx

URL: https://github.com/https://github.abc.com/git-repo/postman/commit/62fccc3932fb51477eda97e1569e9c75060c99e5

--

add_git_metadata_url() {
  local commit=$(git rev-parse HEAD)
  local origin=$(git remote get-url --all origin) 2> /dev/null

  if echo $origin | grep github.com > /dev/null; then

    # git@github.com:concourse/git-resource.git     -> concourse/git-resource
    # https://github.com/concourse/git-resource.git -> concourse/git-resource
    local ownerRepo=$(echo $origin | sed -e' s/.*github.com[:\/]//; s/\.git$//')
    local url=$(echo "**https://github.com/**$ownerRepo/commit/$commit" | jq -R . )

    jq ". + [
        {name: \"url\", value: ${url}}
    ]"
  else
    jq ". + []"
  fi
}

**Comment by agurney** [comment]
The example has `github.abc.com` but this actually affects just those URLs that have `github.com` anywhere in them, such as a GitHub Enterprise installation at `github.companyname.com`. The test could look for `(git@|https://)github.com[:/]` or something, in order to only catch genuine github.com URLs, and that would at least stop this particular example from triggering.

Aside from that I don't see a good general way to discover an "clickable commit URL" corresponding to a given hash and remote. I can _imagine_ actively probing something derived from the remote URL, in order to find out "aha, this is GitHub Enterprise, I'd better generate a clickable URL of the proper form". Or the resource gains a configuration knob for the URL pattern. But neither of these seem very attractive.

**Comment by vinhtran2905** [comment]
It works perfectly. Thanks for the fix.
