### ISSUE TITLE
Bump version to fix git vurnerability

### ISSUE THREAD

**Issue by raghu999** [concourse/git-resource#317]
Github published security advisory which describes high severity bug in git client. A bump to resource version will install the latest version of git client [GHSA-qm7j-c969-7j4q ](https://github.com/git/git/security/advisories/GHSA-qm7j-c969-7j4q)

**Comment by YoussB** [comment]
@raghu999 thanks for reporting. sorry for the late response. 
This made it through to version 1.7.1.

I know it is not shown in the release notes, but this is only because the release notes only track the changes in the resource code, but not the git binary.

```
docker run concourse/git-resource:1.7.1 git --version
git version 2.26.2
```

I will close this, but let me know if it needs to be reopened.
